### ISSUE TITLE
ESLint parsing error

### ISSUE THREAD

**Issue by sergeh** [samuelmeuli/lint-action#36]
I just got this error on an action and I'm not sure what's causing it, running `eslint --no-color --format json "."` outputs no error.

```
 Error: ESLint error: Parsing error: Unexpected token ...
    at Function.parseOutput (/home/runner/work/_actions/samuelmeuli/lint-action/v1/src/linters/eslint.js:86:12)
    at runAction (/home/runner/work/_actions/samuelmeuli/lint-action/v1/src/index.js:86:30)
/home/runner/work/_actions/samuelmeuli/lint-action/v1/src/index.js:16
	throw new Error(`Exiting because of unhandled promise rejection`);
	^

Error: Exiting because of unhandled promise rejection
    at process.<anonymous> (/home/runner/work/_actions/samuelmeuli/lint-action/v1/src/index.js:16:8)
    at process.emit (events.js:210:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)
```

**Comment by sergeh** [comment]
Closing issue, this was due to `eslint-plugin-vue` requiring custom `parserOptions`
