### ISSUE TITLE
I have defined es6 version in my file though I am getting this when running action in github

### ISSUE THREAD

**Issue by chaudharykiran** [samuelmeuli/lint-action#37]
Error: ESLint error: Parsing error: The keyword 'const' is reserved
    at Function.parseOutput (/home/runner/work/_actions/samuelmeuli/lint-action/v1/src/linters/eslint.js:86:12)
    at runAction (/home/runner/work/_actions/samuelmeuli/lint-action/v1/src/index.js:86:30)

**Comment by samuelmeuli** [comment]
This is an error with your ESLint setup. You can run the [ESLint command](https://github.com/samuelmeuli/lint-action/blob/82ccadc7026bcdf40b193e8a599b7467b3e1c6e0/src/linters/eslint.js#L44-L55) locally to debug your issue.
