### ISSUE TITLE
Not able to get the lint action working on python

### ISSUE THREAD

**Issue by jayanthchandra** [samuelmeuli/lint-action#41]
Hi, 

I followed up the configuration for Python Setup but it breaks when it starts linting process. 
PFB Error trace

Adding auth information to Git remote URL
/bin/sh: 1: Syntax error: "(" unexpected
Error: Command failed: git remote set-url origin https://jayanthchandra:***@github.com/jayanthchandra/boilerPlate-flask.git
/bin/sh: 1: Syntax error: "(" unexpected

    at checkExecSyncError (child_process.js:621:11)
    at execSync (child_process.js:657:15)
    at run (/home/runner/work/_actions/samuelmeuli/lint-action/v1/src/utils/action.js:69:18)
    at Object.checkOutRemoteBranch (/home/runner/work/_actions/samuelmeuli/lint-action/v1/src/git.js:17:3)
    at runAction (/home/runner/work/_actions/samuelmeuli/lint-action/v1/src/index.js:54:7)
    at Object.<anonymous> (/home/runner/work/_actions/samuelmeuli/lint-action/v1/src/index.js:113:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14) {
  status: 2,
  signal: null,
  output: [ null, '', '/bin/sh: 1: Syntax error: "(" unexpected\n' ],
  pid: 2555,
  stdout: '',
  stderr: '/bin/sh: 1: Syntax error: "(" unexpected\n'
}
/home/runner/work/_actions/samuelmeuli/lint-action/v1/src/index.js:13
	throw new Error(`Exiting because of unhandled promise rejection`);

Error: Exiting because of unhandled promise rejection
    at process.<anonymous> (/home/runner/work/_actions/samuelmeuli/lint-action/v1/src/index.js:13:8)
    at process.emit (events.js:210:5)
    at processPromiseRejections (internal/process/promises.js:201:33)
    at processTicksAndRejections (internal/process/task_queues.js:94:32)

Is there any workaround for this ? 

I tried both v1 and v1.5 but still has the same error.

**Comment by samuelmeuli** [comment]
You're not passing in the GitHub token:

```diff

        - name: Run linters
          uses: samuelmeuli/lint-action@v1
          with:
-           github_token: ${{ secrets.TEST }}
+           github_token: ${{ secrets.github_token }}
            black: true
            flake8: true
```
